Web/Shop.Web/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Web.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [MinLength(5)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        [MaxLength(250 , ErrorMessage="Too long")]
        public string Message { get; set; }
    }
}

Web/Shop.Web/Controllers/ArtProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Shop.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Shop.Data.Models;
using Shop.Web.ViewModels;
using Shop.Services.Data;
using Microsoft.AspNetCore.Identity;
using Shop.Web.ViewModels.ArtProducts;
using Microsoft.AspNetCore.Authorization;
using Shop.Services;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using CloudinaryDotNet;

namespace Shop.Web.Controllers
{
    public class ArtProductsController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly IArtProductsService artProductsService;
        private readonly ICategoriesService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMailService mailService;
        private readonly ICloudinaryService cloudinaryService;
        private readonly Cloudinary cloudinary;

        public ArtProductsController(
            ApplicationDbContext context,
            IArtProductsService artProductsService,
            ICategoriesService categoriesService,
            UserManager<ApplicationUser> userManager,
            IMailService mailService,
            ICloudinaryService cloudinaryService,
            Cloudinary cloudinary)
        {
            this.context = context;
            this.artProductsService = artProductsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
            this.mailService = mailService;
            this.cloudinaryService = cloudinaryService;
            this.cloudinary = cloudinary;
        }

        public IActionResult ById(int id)
        {
            var artProductViewModel = this.artProductsService.GetById<ArtProductViewModel>(id);
            if (artProductViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(artProductViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            var viewModel = new ArtProductCreateInputModel
            {
                Categories = categories,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(ArtProductCreateInputModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }


            var imageLinks = await this.cloudinaryService.UploadAsync(this.cloudinary, input.ImageLinks);
            List<ImageOfProduct> productsimages = new List<ImageOfProduct>();

            foreach (var image in imageLinks)
            {
                ImageOfProduct imageProduct = new ImageOfProduct();
                imageProduct.Link = image;
                productsimages.Add(imageProduct);
            }

            var artProductId = await this.artProductsService.CreateAsync(
                input.Title, input.Size, input.Price, input.ArtDescription, input.ArtCreatedDate, productsimages,
                input.CategoryId, user.Id, input.Artist.Name, input.Artist.Nationality, input.Artist.Biography,
                input.Artist.BirthDate, input.Artist.DeathDate);

            this.TempData["InfoMessage"] = "ArtProduct has been listed!";

            await this.mailService.SendEmailAsync(user.Email, "hello,there!", "Product Created!");

            return this.RedirectToAction(nameof(this.ById), new { id = artProductId });
        }
    }
}

Web/Shop.Web/Controllers/HomeController.cs
namespace Shop.Web.Controllers
{
    using System.Diagnostics;
    using Shop.Data;
    using Shop.Web.ViewModels;

    using Microsoft.AspNetCore.Mvc;
    using Shop.Services;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;
    using Shop.Web.ViewModels.Home;
    using Shop.Services.Data;
    using Microsoft.AspNetCore.Http;
    using System.Threading.Tasks;

    using CloudinaryDotNet;
    using System.Collections.Generic;

    using Microsoft.EntityFrameworkCore;


    public class HomeController : BaseController
    {
        private readonly IMailService mailService;
        private readonly ApplicationDbContext context;
        private readonly ICategoriesService categoriesService;
        private readonly Cloudinary cloudinary;
        private readonly ICloudinaryService cloudinaryService;


        // TODO vkarvame dbcontex-a v constructor-a, za da mojem da polzvame dannite ot bazata v actioni-te. 
        public HomeController(IMailService mailService, ApplicationDbContext context, ICategoriesService categoriesService, Cloudinary cloudinary, ICloudinaryService cloudinaryService)
        {
            this.mailService = mailService;
            this.context = context;
            this.categoriesService = categoriesService;
            this.cloudinary = cloudinary;
            this.cloudinaryService = cloudinaryService;
        }

        public async Task<IActionResult> Search(string searchString)
        {
            var arts = from a in this.context.ArtProducts.Include(a => a.Artist).Include(a => a.Category).Include(a=> a.ImageLinks)
                       select a;

            if (!string.IsNullOrEmpty(searchString))
            {
                arts = arts.Where(s => s.Title.Contains(searchString) || s.Artist.Name.Contains(searchString));
            }

            var artVM = new ArtProductSearchViewModel
            {
                ArtProducts = await arts.ToListAsync(),
            };

            return this.View(artVM);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(ICollection<IFormFile> files)
        {

            await this.cloudinaryService.UploadAsync(this.cloudinary, files);

            return this.Redirect("/");
        }


        public IActionResult Index()
        {
            this.HttpContext.Session.SetString("Name", "Marin");

            var viewModel = new IndexViewModel
            {
                Categories =
                     this.categoriesService.GetAll<IndexCategoryViewModel>(),
            };
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

        public IActionResult Contact()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            // Pravi proverka dali propertytata ot ContactViewModel sa validni
            // Tova e validaciqta na server-side, dokato attributite sa na clienskata chast.
            if (this.ModelState.IsValid)
            {
                // send the email
                this.mailService.SendEmailAsync(model.Email, model.Subject, model.Message);
                this.ViewBag.UserMessage = "Mail Sent";

                // za da izchistim polencatata, kudeto sme vuvejdali.
                this.ModelState.Clear();
            }

            return this.View();
        }

        public IActionResult About()
        {
            this.ViewBag.Title = "About us";

            return this.View();
        }

        [Authorize]
        public IActionResult Shop()
        {
            var results = this.context.ArtProducts
                .OrderBy(p => p.Category)
                .ToList();

            // TODO taka shte izpolzvame dannite ot bazata vuv view-to.
            return this.View(results);
        }


    }
}

Web/Shop.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h2>About us</h2>
<p>More to follow</p>

Web/Shop.Web/Views/Home/Contact.cshtml
@using Shop.Common
@model Shop.Web.ViewModels.ContactViewModel
@{
    ViewData["Title"] = "Contact";
}
<!--Dobavqme samo scriptovete, koito iskame.-->
@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}
<h2 class="text-center">Contact us</h2>
<div class="col-md-6 offset-md-3">
    <link href="lib/@@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <div class="card card-body bg-light">
        <form method="post">
            <!-- asp-for sluji za namapvane na poletata kum viewModel-a i sushto taka dava vuzmojnost pri cukane vurhu imeto na poleto da te vkarva v poleto za pisane.-->
            <!-- Poleta za vuvejdane na danni -->
            <!--Shte pokaje samo greshkite, koito sme imali opitvaiki se da izpulnim deistvieto.-->
            <!--Spanovete pokazvat greshkite za vsqko pole, koito sa v rezultat na validaciite.-->
            <div asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <label asp-for="Name">Username: </label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <!--Ako iskame speicalen design na dadeno pole. <input style="font-size: 18px; width=: 200px;" /> -->
            <div class="form-group">
                <label asp-for="Email">Email: </label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject">Subject: </label>
                <input type="text" asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message">Message: </label>
                <textarea rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Send Message</button>
                <div class="text-success">@ViewBag.UserMessage</div>
            </div>

        </form>
    </div>
</div>

Web/Shop.Web/Views/Home/Index.cshtml
@using Shop.Common
@model Shop.Web.ViewModels.Home.IndexViewModel
@{
    this.ViewData["Title"] = "Home Page";

}



<div class="row">
    <div class="col-md-9">
        <div class="text-center">
            <h1 class="display-4">Welcome to @GlobalConstants.SystemName!</h1>
        </div>

        <a asp-controller="ArtProducts" asp-action="Create" class="btn btn-primary btn-lg">Create ArtProduct</a>

        <div class="row">
            @foreach (var category in Model.Categories)
            {<div class="col-md-4 media">
                    <img src="@category.ImageUrl" width="100" class="mr-3" alt="@category.Name">
                    <div class="media-body">
                        <h5 class="mt-0">
                            <a href="@category.Url">
                                @category.Name
                            </a>
                        </h5>

                    </div>
                </div>
            }
        </div>


        <div class="product-info">
            <img src="~/img/Egypt.jpg" />
            <strong>Tutankamon</strong>
            <ul class="product-props">
                <li>Price: 9.99$</li>
                <li>Artist: Van Gogh</li>
                <li>Title: </li>
                <li>Description: Self-Portrait</li>
            </ul>
            <button id="buybutton" class="btn btn-success">Buy</button>

        </div>
        <br />
        <br />
        <div id="theform">
            <form>
                <!-- Poleta za vuvejdane na danni -->
                <label>Username: </label>
                <br />
                <input />
                <!--Ako iskame speicalen design na dadeno pole. <input style="font-size: 18px; width=: 200px;" /> -->
                <!--Taka minava na drugiq red <br /> -->
                <br />
                <label>Password: </label>
                <br />
                <input type="password" />
                <br />
                <label>Email: </label>
                <br />
                <input type="email" />
                <br />
                <label>Subject: </label>
                <br />
                <input type="text" />
                <br />
                <label>Message: </label>
                <br />
                <textarea rows="4"></textarea>
                <br />
                <input type="submit" value="Send Message" />
                <br />
            </form>
        </div>


        <div>
            <div id="LoginToggle">Login</div>
            <form class="Popup-form">
                <div>
                    <label>Username</label>
                    <input />
                </div>
                <div>
                    <label>Password</label>
                    <input type="password" />
                </div>
                <div>
                    <input type="checkbox" />
                    <label>Remember me</label>
                </div>
                <div>
                    <input type="submit" value="Login" />
                </div>
            </form>
        </div>

        <button class="btn waves-effect waves-light" type="submit" name="action">
            Submit
            <i class="material-icons right">send</i>
        </button>

        <a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">+</i></a>

        <div class="row">
            <div class="input-field col s6">
                <input value="Alvin" id="first_name2" type="text" class="validate">
                <label class="active" for="first_name2">First Name</label>
            </div>
        </div>
        <script>
            $(document).ready(function () {
                M.updateTextFields();
            });
        </script>


        <form action="#">
            <div class="file-field input-field">
                <div class="btn">
                    <span>File</span>
                    <input type="file" multiple>
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="Upload one or more files">
                </div>
            </div>
        </form>

      

        
        <div class="filter categories"><h6 class="mt0 margin-b-7">Category</h6><a href="/en/artworks/" class="block-link block h6"><i class="fal fa-circle"></i>All mediums</a><a href="/en/artworks/painting/" class="block-link block h6"><i class="fal fa-circle"></i>Painting</a><a href="/en/artworks/photography/" class="block-link block h6"><i class="fas fa-circle"></i>Photography</a><a href="/en/artworks/sculpture/" class="block-link block h6"><i class="fal fa-circle"></i>Sculpture</a><a href="/en/artworks/prints/" class="block-link block h6"><i class="fal fa-circle"></i>Prints</a><a href="/en/artworks/work-on-paper/" class="block-link block h6"><i class="fal fa-circle"></i>Work on paper</a><a href="/en/artworks/textile/" class="block-link block h6"><i class="fal fa-circle"></i>Textile</a><a href="/en/artworks/new-media/" class="block-link block h6"><i class="fal fa-circle"></i>New Media</a><a href="/en/artworks/design/" class="block-link block h6"><i class="fal fa-circle"></i>Design</a><a href="/en/artworks/jewelry/" class="block-link block h6"><i class="fal fa-circle"></i>Jewelry</a><a href="/en/artworks/illustration/" class="block-link block h6"><i class="fal fa-circle"></i>Illustration</a></div>
    </div>
</div>

Web/Shop.Web/Views/Home/Search.cshtml
@model Shop.Web.ViewModels.ArtProductSearchViewModel


@foreach (var item in Model.ArtProducts)
{
    <div class="col-md-3">
        <div class="border bg-light rounded p-1">
            @foreach (var pic in item.ImageLinks)
            {
                <img src="@pic.Link" class="img-fluid" alt="@item.Title" />
            }


            <h3>Title: @item.Title</h3>
            <ul>
                <li></li>
                <li>Price: @item.Price</li>
                <li>Artist: @item.Artist.Name</li>
                <li>Size: @item.Size</li>
                <li>Description: @Html.Raw(item.ArtDescription)</li>
                <li>ArtCreatedOn: @item.ArtCreatedDate.Year</li>
                <h2 class="media-heading"><a asp-controller="ArtProducts" asp-action="ById" asp-route-id="@item.Id">More Info</a></h2>
            </ul>
            <button id="buybutton" class="btn btn-success">Buy</button>
            <button type="button" class="btn btn-primary" id="complete-order-button">Complete</button>
        </div>
    </div>

    }

Web/Shop.Web/Views/Home/Shop.cshtml
<!--Pozvolqva ni da izpolzvame c# sintaktis za product propertitata.-->
@using Shop.Data.Models;
@model IEnumerable<ArtProduct>

@{
    ViewData["Title"] = "Shop";
}

<h1>Shop</h1>
<p>Count: @Model.Count()</p>

<!--Shte napravi listing-a s 4 item-a na red, zashtoto ediniq product zaema 3 mesta.-->
<div class="row">
    @foreach (var p in Model)
    {
        <div class="col-md-3">
            <div class="border bg-light rounded p-1">
                <img src="~/img/Egypt.jpg" class="img-fluid" alt="@p.Title" />
                <h3>@p.Category - @p.Size</h3>
                <ul>
                    <li>Price: @p.Price</li>
                    <li>Artist: @p.Artist</li>
                    <li>Title: @p.Title</li>
                    <li>Description: @p.ArtDescription</li>
                </ul>
                <button id="buybutton" class="btn btn-success">Buy</button>
            </div>
        </div>
    }
</div>